---
ID: "1867801e-593f-4697-8de9-240240153424"
Parent: "6f4a634c-3a34-4434-9d99-0c9f24201fb4"
Template: "6f4a634c-3a34-4434-9d99-0c9f24201fb4"
Path: /sitecore/templates/Feature/Foodly/Page Content/Event/Music Event Section/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250726T175751Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d3da4e4c-d5e1-45d9-aa06-8f55392a2c99"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250728T072158Z
    - ID: "e47ae32c-05c4-4637-aa11-71df800fd228"
      Hint: sectionTitle
      Value: $name
