---
ID: "10f663db-04d7-4731-8139-5cbaffe4bf0b"
Parent: "79724624-9093-4abd-b1e1-50e1f81c5c40"
Template: "79724624-9093-4abd-b1e1-50e1f81c5c40"
Path: /sitecore/templates/Feature/Foodly/Page Content/Button/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250723T122936Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "72ae4975-65fe-43d2-a91c-81a5f0b2ff0d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250723T122936Z
