---
ID: "b9d3f315-51b4-4d56-a813-22b024bd4d8e"
Parent: "b6607d24-3c25-47dc-a2b7-1b5abba944a2"
Template: "b6607d24-3c25-47dc-a2b7-1b5abba944a2"
Path: /sitecore/templates/Feature/Foodly/Page Content/Rendering Parameters/Event Address/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c5adf4ef-f6ef-494d-9469-e7009f6447dd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250728T093721Z
