---
ID: "28295bcb-cafa-4599-a0cc-6a72f128d1a7"
Parent: "ba7b1eda-943b-4570-bfee-e972cebc0477"
Template: "ba7b1eda-943b-4570-bfee-e972cebc0477"
Path: /sitecore/templates/Feature/Foodly/Page Content/Event/Event Card Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8A4CD53C-8929-47F8-8223-EEF33BBEF4F3}
    {BA7B1EDA-943B-4570-BFEE-E972CEBC0477}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f7ebddcd-7f5b-4012-8ca1-460f73ce6898"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250726T190249Z
