---
ID: "36c228bb-597b-4d1a-853c-e83baf6b628c"
Parent: "796203f1-72d5-427f-950b-44cfaff922f1"
Template: "796203f1-72d5-427f-950b-44cfaff922f1"
Path: /sitecore/templates/Feature/Foodly/Page Content/Rendering Parameters/Event Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea67baa4-9998-4e86-8e6b-f61b67fbba90"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250726T190248Z
